version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
